services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - default
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - default
    volumes:
      - '~/.minio:/data'
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_pasword
      - MINIO_DEFAULT_BUCKETS=your_bucket_name

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      - default
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'

networks:
  default:
    driver: bridge
  default_minio:
    driver: bridge
  default_nginx:
    driver: bridge

volumes:
  minio_data:
  nginx_data:


